# Generated by Django 3.0.6 on 2020-05-31 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trade_trans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_ratio', models.FloatField(default=0.05, verbose_name='BreakEven Ratio (BE RATIO)')),
                ('risk_threshold', models.FloatField(default=0.075, verbose_name='Risk Threshold')),
                ('trans_auto_correlate', models.PositiveIntegerField(default=10, verbose_name='Transactions to Wait before Correlating')),
            ],
        ),
        migrations.CreateModel(
            name='TradeRqst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField(error_messages={'unique': 'Another Request with a similar ID exists'}, unique=True, verbose_name='RQSTID')),
                ('wlr', models.FloatField(max_length=7, validators=[trade_trans.models.validate_wlr], verbose_name='Win/Loss Ratio')),
                ('entry_price', models.FloatField(max_length=7, validators=[trade_trans.models.non_neg_or_zero], verbose_name='Entry Point')),
                ('take_profit1', models.FloatField(max_length=7, validators=[trade_trans.models.non_neg_or_zero], verbose_name='Supplied Take Profit1')),
                ('take_profit2', models.FloatField(blank=True, max_length=7, null=True, validators=[trade_trans.models.non_neg_or_zero], verbose_name='Supplied Take Profit2')),
                ('signal_type', models.CharField(choices=[('BL', 'Buy Limit'), ('BS', 'Buy Stop'), ('SS', 'Sell Stop'), ('SL', 'Sell Limit')], max_length=15, verbose_name='Signal Type')),
                ('time_frame', models.CharField(choices=[('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day'), ('1W', '1 Week'), ('1M', '1 Month')], max_length=15, verbose_name='Time Frame')),
                ('stop_loss', models.FloatField(max_length=7, validators=[trade_trans.models.non_neg_or_zero], verbose_name='Stop Loss')),
                ('asset', models.CharField(max_length=15, verbose_name='Asset')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RqAnal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_pd', models.TextField(verbose_name='Risk Calculation Results (DataFrame)')),
                ('risk', models.FloatField(verbose_name='Calculated RISK for Request, x 100 to get %')),
                ('expected_return', models.FloatField(verbose_name='Expected Return , x 100 to get %')),
                ('status', models.CharField(choices=[('WA', 'Waiting'), ('DC', 'Discarded'), ('PR', 'Processed')], max_length=9, verbose_name='Request Status')),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rqst_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_trans.TradeRqst', verbose_name='Trade Request ID')),
            ],
        ),
        migrations.CreateModel(
            name='CorrelationTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=15, verbose_name='Asset')),
                ('issue_time', models.DateTimeField()),
                ('time_frame', models.CharField(choices=[('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day'), ('1W', '1 Week'), ('1M', '1 Month')], max_length=15, verbose_name='Time Frame')),
                ('entry_price', models.FloatField(verbose_name='Entry Price')),
                ('trade_id', models.PositiveIntegerField(verbose_name='Original Trade ID')),
                ('corr_nos', models.PositiveIntegerField(default=0, verbose_name='How many times has this rqst been correlated ?')),
                ('comments', models.TextField()),
                ('status', models.CharField(choices=[('WA', 'Waiting'), ('DC', 'Discarded'), ('PFR', 'Passed For Ranking')], default='WA', max_length=20, verbose_name='Request Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_trans.RqAnal', verbose_name='Forwarded Request Analysis ID')),
            ],
        ),
    ]
